---
micronaut:
    application:
        name: sunrise
    server:
        port: 8082
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
endpoints:
    info:
        enabled: true
        sensitive: false
    health:
        enabled: true
        sensitive: false
tracing:
  zipkin:
    enabled: true
    http:
      url: http://zipkin:9411
    sampler:
      probability: 1


